---
title:  "Utility Bill Summary"
output: blastula::blastula_email
---

```{css, echo=FALSE}
* {
  font-family: Georgia ! Important;
  font-size:1.015em !Important;
}

```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
source("prep.R")
library(gt)
r <- sample(1:14)[1]
nicknames <- c("Beep", "Freak", "Lovey", "Dove", "Crunch",
               "Munch", "Fleep", "Love Dove", "Sug", "Flip", "Dip", "Brown-eyed Freak", "Sweet", "Crunchlax")

greet <- nicknames[r]



```

Hello `r greet`,

This month, your share of the utility bill is: `r paste0("$", round(half$half, 2))`.

For a closer look at our bills this month see the table below: 

```{r, echo=FALSE , out.width='100%', results='asis'}

month_sub |> 
  select(Company = company, 
         Type = type, 
         `Due Date` = due_date, 
         Amount = amount) |> 
  gt::gt() |> 
  gt::fmt_date(columns = `Due Date`, date_style = 5) |> 
  gt::fmt_currency(columns = Amount) |> 
  gt::tab_options(
    table.width = gt::pct(90),    # Set table width to 100% of the document width
    table.align = "center"     # Center-align the table
  ) |> 
  gt::opt_stylize(style = 2)

```

If you want to look at the dashboard I made for our utilities, [you can view it here.](http://192.168.4.107:3838/) You will have to be connected to our wifi to view it.

I love you!

Brenden
