name: ute
on:
  schedule:
    - cron: '0 11 1 * *'  # Note: Fixed the cron syntax
jobs:
  notification:
    runs-on: macOS-latest
    env:
      SMTP2GO_KEY: ${{ secrets.SMTP2GO_KEY }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}
      CC_EMAIL: ${{ secrets.CC_EMAIL }}
      GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      CLIENT_X509_CERT_URL: ${{ secrets.CLIENT_X509_CERT_URL }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
      AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.AUTH_PROVIDER_X509_CERT_URL }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2  # Add this step to install Pandoc
      - name: Install packages
        run: |
          Rscript -e 'install.packages(c(
            "blastula",
            "googlesheets4",
            "lubridate",
            "gt",
            "dplyr",
            "httr",
            "janitor"
          ), dependencies = TRUE)'

      - name: Create email and send
        run: Rscript run.R
