name: ute

on:
  schedule:
    - cron: '45 15 * * *'  # once on the first of the month

jobs:
  notification:
    runs-on: macOS-latest
    env:
      SMTP2GO_KEY: ${{ secrets.SMTP2GO_KEY }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install blastula package
        run: Rscript -e 'install.packages("blastula", dependencies = TRUE)'
      - name: Install googlesheets4 package
        run: Rscript -e 'install.packages("googlesheets4", dependencies = TRUE)'
      - name: Install lubridate package
        run: Rscript -e 'install.packages("lubridate", dependencies = TRUE)'
      - name: Install gt
        run: Rscript -e 'install.packages("gt", dependencies = TRUE)'
      - name: Install dplyr
        run: Rscript -e 'install.packages("dplyr", dependencies = TRUE)'
      - name: Install httr
        run: Rscript -e 'install.packages("httr", dependencies = TRUE)'
      - name: Create email and send
        run: Rscript run.R
