name: ute
on:
  schedule:
    - cron: '10 16 * * *'  # Note: Fixed the cron syntax
jobs:
  notification:
    runs-on: macOS-latest
    env:
      SMTP2GO_KEY: ${{ secrets.SMTP2GO_KEY }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2  # Add this step to install Pandoc
      - name: Install packages
        run: |
          Rscript -e 'install.packages(c(
            "blastula",
            "googlesheets4",
            "lubridate",
            "gt",
            "dplyr",
            "httr"
          ), dependencies = TRUE)'
          
      - name: Create email and send
        run: Rscript run.R

